import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#24382C",
        "on-primary": "#F4EFE4",
        "primary-container": "#31503D",
        "on-primary-container": "#c5d5ad",
        secondary: "#B08D57",
        "on-secondary": "#F4EFE4",
        "secondary-container": "#C7A86A",
        "on-secondary-container": "#24382C",
        tertiary: "#4d4024",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#655739",
        surface: "#EFE8D8",
        "on-surface": "#2A2A26",
        "surface-dim": "#ddd3ba",
        "surface-bright": "#EFE8D8",
        "surface-container-lowest": "#F4EFE4",
        "surface-container-low": "#F4EFE4",
        "surface-container": "#EAE2D0",
        "surface-container-high": "#E7EADF",
        "surface-container-highest": "#E6DEC8",
        "surface-variant": "#E6DEC8",
        "on-surface-variant": "#54604F",
        "on-background": "#2A2A26",
        background: "#EFE8D8",
        outline: "#B6AB8E",
        "outline-variant": "#DDD3BA",
        "inverse-surface": "#1C2C22",
        "inverse-on-surface": "#EAE3D2",
        "inverse-primary": "#bccca4",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-tint": "#556343",
      },
      fontFamily: {
        headline: ["var(--font-cormorant)", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.5rem",
        md: "0.75rem",
        lg: "1.125rem",
        xl: "1.5rem",
      },
      boxShadow: {
        botanical: "0 12px 40px rgba(36, 56, 44, 0.08)",
        "botanical-lg": "0 30px 60px -20px rgba(36, 56, 44, 0.35)",
      },
    },
  },
  plugins: [],
};
export default config;
